<?php $page = 'fba-auto'; ?>
@extends('layout.mainlayout_admin')
@section('title', 'FBA Shipment')
@section('content')

<div class="page-wrapper">
    <div class="content container-fluid">
        
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">FBA Shipment</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.warranty.management') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">FBA Shipment</li>
                    </ul>
                </div>
                <div class="col-auto">
                    <button type="button" class="btn btn-primary" onclick="openCreateModal()">
                        <i class="fe fe-plus"></i> Add New FBA Shipment
                    </button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xl-3 col-sm-6 col-12 d-flex">
                <div class="card bg-comman w-100">
                    <div class="card-body">
                        <div class="db-widgets d-flex justify-content-between align-items-center">
                            <div class="db-info">
                                <h6>Total Shipments</h6>
                                <h3>{{ $stats['total'] ?? 0 }}</h3>
                            </div>
                            <div class="db-icon">
                                <i class="fe fe-box"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 col-12 d-flex">
                <div class="card bg-comman w-100">
                    <div class="card-body">
                        <div class="db-widgets d-flex justify-content-between align-items-center">
                            <div class="db-info">
                                <h6>Pending</h6>
                                <h3>{{ $stats['pending'] ?? 0 }}</h3>
                            </div>
                            <div class="db-icon">
                                <i class="fe fe-clock"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 col-12 d-flex">
                <div class="card bg-comman w-100">
                    <div class="card-body">
                        <div class="db-widgets d-flex justify-content-between align-items-center">
                            <div class="db-info">
                                <h6>Processing</h6>
                                <h3>{{ $stats['processing'] ?? 0 }}</h3>
                            </div>
                            <div class="db-icon">
                                <i class="fe fe-refresh-cw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 col-12 d-flex">
                <div class="card bg-comman w-100">
                    <div class="card-body">
                        <div class="db-widgets d-flex justify-content-between align-items-center">
                            <div class="db-info">
                                <h6>Delivered</h6>
                                <h3>{{ $stats['delivered'] ?? 0 }}</h3>
                            </div>
                            <div class="db-icon">
                                <i class="fe fe-check-circle"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Shipments List</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="fba-auto-table" class="table table-striped table-bordered w-100">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>FBA Shipment ID</th>
                                <th>FBA Shipment Date</th>
                                <th>Product</th>
                                <th>Qty</th>
                                <th>State</th>
                                <th>Warehouse Name</th>
                                <th>QTY Price</th>
                                <th>Generated By</th>
                                <th>Generated At</th>
                                <th>Updated By</th>
                                <th>Updated At</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@include('admin.modules.fba-auto.partials.modals')
@endsection

@push('scripts')
<script>
var productRowIndex = 0;

function openCreateModal() {
    productRowIndex = 0;
    $('#product-rows').empty();
    addProductRow();
    initFbaSelect2($('#createModal'));
    $('#createModal').modal('show');
}

function addProductRow() {
    var idx = productRowIndex++;
    var row = `<tr id="row-${idx}">
        <td class="text-center row-num"></td>
        <td>
            <select name="items[${idx}][product_name]" class="form-select product-ajax-select2 w-100" style="width:100%" required>
                <option value=""></option>
            </select>
        </td>
        <td>
            <input type="number" name="items[${idx}][qty]" class="form-control form-control-sm" min="1" placeholder="0" required>
        </td>
        <td>
            <input type="number" name="items[${idx}][qty_price]" class="form-control form-control-sm" step="0.01" min="0" max="1000000000" placeholder="0.00" required>
        </td>
        <td class="text-center">
            <button type="button" class="btn btn-sm btn-outline-danger remove-row-btn" data-row="${idx}">
                <i class="fe fe-trash-2"></i>
            </button>
        </td>
    </tr>`;
    $('#product-rows').append(row);
    initProductSelect2($(`#row-${idx} .product-ajax-select2`));
    updateRowNumbers();
}

function updateRowNumbers() {
    $('#product-rows tr').each(function(i) {
        $(this).find('.row-num').text(i + 1);
    });
}

var editProductRowIndex = 0;

function addEditProductRow() {
    var idx = 'n' + editProductRowIndex++;
    var row = `<tr>
        <td class="text-center row-num"></td>
        <td>
            <select name="items[${idx}][product_name]" class="form-select edit-product-select2 w-100" style="width:100%" required>
                <option value=""></option>
            </select>
        </td>
        <td>
            <input type="number" name="items[${idx}][qty]" class="form-control form-control-sm" min="1" placeholder="0" required>
        </td>
        <td>
            <input type="number" name="items[${idx}][qty_price]" class="form-control form-control-sm" step="0.01" min="0" max="1000000000" placeholder="0.00" required>
        </td>
        <td class="text-center">
            <button type="button" class="btn btn-sm btn-outline-danger remove-edit-row-btn">
                <i class="fe fe-trash-2"></i>
            </button>
        </td>
    </tr>`;
    $('#edit-product-rows').append(row);
    initProductSelect2($('#edit-product-rows tr:last .edit-product-select2'), $('#editModal'));
    updateEditRowNumbers();
}

function updateEditRowNumbers() {
    $('#edit-product-rows tr').each(function(i) {
        $(this).find('.row-num').text(i + 1);
    });
}

function initProductSelect2($el, $modal) {
    $modal = $modal || $('#createModal');
    $el.select2({
        width: '100%',
        placeholder: 'Search or type product name',
        allowClear: true,
        tags: true,
        dropdownParent: $modal,
        ajax: {
            url: '{{ route('admin.fba-auto.products.search') }}',
            dataType: 'json',
            delay: 150,
            data: function(params) { return { q: params.term || '' }; },
            processResults: function(data) { return data; },
            cache: false
        },
        minimumInputLength: 0,
        createTag: function(params) {
            var term = $.trim(params.term);
            if (!term) return null;
            return { id: term, text: term, isNew: true };
        },
        templateResult: function(data) {
            if (data.isNew) {
                return $('<span><i class="fe fe-plus-circle me-1 text-primary"></i>Add: <strong>' + data.text + '</strong></span>');
            }
            return data.text;
        }
    });

    $el.on('select2:open', function() {
        setTimeout(function() {
            var $searchInput = $('.select2-container--open .select2-search__field');
            if ($searchInput.length) {
                $searchInput[0].dispatchEvent(new Event('input', { bubbles: true }));
            }
        }, 50);
    });
}

$(function () {
    initFbaSelect2($(document));

    $('#fba-auto-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ route('admin.fba-auto.ajax') }}',
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'shipment_id', name: 'shipment_id'},
            {data: 'shipment_date', name: 'shipment_date'},
            {data: 'product_name', name: 'product_name'},
            {data: 'qty', name: 'qty'},
            {data: 'state', name: 'state'},
            {data: 'warehouse_name', name: 'warehouse_name'},
            {data: 'qty_price', name: 'qty_price'},
            {data: 'generated_by', name: 'generated_by', orderable: false, searchable: false},
            {data: 'generated_at', name: 'created_at'},
            {data: 'updated_by', name: 'updated_by', orderable: false, searchable: false},
            {data: 'updated_at', name: 'updated_at'},
            {data: 'status', name: 'status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
        order: [[1, 'desc']]
    });
});

function initFbaSelect2($scope) {
    $scope.find('.fba-select2').each(function() {
        const $select = $(this);
        const $modal = $select.closest('.modal');

        if ($select.hasClass('select2-hidden-accessible')) {
            $select.select2('destroy');
        }

        $select.select2({
            width: '100%',
            tags: $select.data('tags') === true || $select.data('tags') === 1,
            placeholder: $select.data('placeholder') || 'Select option',
            allowClear: true,
            dropdownParent: $modal.length ? $modal : $(document.body)
        });
    });
}

$(document).on('click', '.edit-btn', function() {
    let id = $(this).data('id');
    $.ajax({
        url: `/admin/fba-auto/edit/${id}`,
        type: 'GET',
        success: function(response) {
            $('#edit-content').html(response);
            initFbaSelect2($('#editModal'));
            // Init product select2 on existing rows
            $('#editModal .edit-product-select2').each(function() {
                initProductSelect2($(this), $('#editModal'));
            });
            // Counter starts after existing rows so new row indices don't clash
            editProductRowIndex = $('#edit-product-rows tr').length;
            $('#editModal').modal('show');
        },
        error: function() {
            toastr.error('Failed to load data');
        }
    });
});

$(document).on('click', '.delete-btn', function() {
    let id = $(this).data('id');
    Swal.fire({
        title: 'Are you sure?',
        text: 'This action cannot be undone!',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#dc3545',
        cancelButtonColor: '#6c757d',
        confirmButtonText: 'Yes, Delete!'
    }).then((result) => {
        if (result.isConfirmed) {
            $.ajax({
                url: `/admin/fba-auto/delete/${id}`,
                type: 'DELETE',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function(response) {
                    if (response.success) {
                        toastr.success('Deleted successfully');
                        $('#fba-auto-table').DataTable().ajax.reload();
                    } else {
                        toastr.error(response.message);
                    }
                }
            });
        }
    });
});

$(document).on('click', '#add-product-row', function() {
    addProductRow();
});

$(document).on('click', '.remove-row-btn', function() {
    if ($('#product-rows tr').length === 1) {
        toastr.warning('At least one product row is required');
        return;
    }
    $(this).closest('tr').remove();
    updateRowNumbers();
});

$('#create-form').on('submit', function(e) {
    e.preventDefault();
    let formData = new FormData(this);

    $.ajax({
        url: '{{ route('admin.fba-auto.store') }}',
        type: 'POST',
        data: formData,
        processData: false,
        contentType: false,
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        success: function(response) {
            if (response.success) {
                toastr.success(response.message);
                $('#createModal').modal('hide');
                $('#fba-auto-table').DataTable().ajax.reload();
            } else {
                toastr.error(response.message);
            }
        },
        error: function(xhr) {
            let msg = xhr.responseJSON?.message || 'Error occurred';
            let errors = xhr.responseJSON?.errors;
            if (errors) {
                msg = Object.values(errors).flat().join('<br>');
            }
            toastr.error(msg);
        }
    });
});

$(document).on('click', '#add-edit-product-row', function() {
    addEditProductRow();
});

$(document).on('click', '.remove-edit-row-btn', function() {
    if ($('#edit-product-rows tr').length === 1) {
        toastr.warning('At least one product row is required');
        return;
    }
    $(this).closest('tr').remove();
    updateEditRowNumbers();
});

$(document).on('submit', '#edit-form', function(e) {
    e.preventDefault();
    let id = $('#edit_id').val();
    let formData = new FormData(this);

    $.ajax({
        url: `/admin/fba-auto/update/${id}`,
        type: 'POST',
        data: formData,
        processData: false,
        contentType: false,
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        success: function(response) {
            if (response.success) {
                toastr.success(response.message);
                $('#editModal').modal('hide');
                $('#fba-auto-table').DataTable().ajax.reload();
            } else {
                toastr.error(response.message);
            }
        },
        error: function(xhr) {
            let msg = xhr.responseJSON?.message || 'Error occurred';
            let errors = xhr.responseJSON?.errors;
            if (errors) {
                msg = Object.values(errors).flat().join('<br>');
            }
            toastr.error(msg);
        }
    });
});

$('#createModal').on('hidden.bs.modal', function() {
    $('#create-form')[0].reset();
    $('#create-form .fba-select2').val(null).trigger('change');
    $('#product-rows').empty();
    productRowIndex = 0;
});

$('#editModal').on('hidden.bs.modal', function() {
    const form = $(this).find('form')[0];
    if (form) form.reset();
    $(this).find('.fba-select2').val(null).trigger('change');
});
</script>
@endpush
