<?php $page = 'fba-auto'; ?>
@extends('layout.mainlayout_admin')
@section('title', 'FBA Shipment Details')
@section('content')

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">FBA Shipment Details</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.warranty.management') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.fba-auto.index') }}">FBA Shipment</a></li>
                        <li class="breadcrumb-item active">Details</li>
                    </ul>
                </div>
                <div class="col-auto">
                    <a href="{{ route('admin.fba-auto.index') }}" class="btn btn-secondary">
                        <i class="fe fe-arrow-left"></i> Back
                    </a>
                </div>
            </div>
        </div>

        @if (!$shipment)
            <div class="alert alert-warning">FBA shipment not found.</div>
        @else
            <div class="row">
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex align-items-center justify-content-between flex-wrap gap-2">
                                <h4 class="card-title mb-0">{{ $shipment->shipment_id }}</h4>
                                {!! $shipment->status_badge !!}
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">FBA Shipment Date</div>
                                    <div>{{ $shipment->shipment_date ? $shipment->shipment_date->format('d-M-Y') : '-' }}</div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">Product</div>
                                    <div>{{ $shipment->product_name ?? '-' }}</div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">Qty</div>
                                    <div>{{ number_format($shipment->qty ?? 0) }}</div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">State</div>
                                    <div>{{ $shipment->state ?? '-' }}</div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">Warehouse Name</div>
                                    <div>{{ $shipment->warehouse_name ?? '-' }}</div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">QTY Price</div>
                                    <div>{{ $shipment->formatted_price }}</div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">Generated By</div>
                                    <div>{{ $shipment->generator->username ?? $shipment->generator->name ?? 'System' }}</div>
                                    <small class="text-muted">{{ $shipment->created_at ? $shipment->created_at->format('d-M-Y H:i') : '-' }}</small>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="fw-bold">Last Updated By</div>
                                    <div>{{ $shipment->updater->username ?? $shipment->updater->name ?? '-' }}</div>
                                    <small class="text-muted">{{ $shipment->updater && $shipment->updated_at ? $shipment->updated_at->format('d-M-Y H:i') : '-' }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title mb-0">Change History</h4>
                        </div>
                        <div class="card-body">
                            @if(($shipment->activities ?? collect())->isEmpty())
                                <div class="text-muted">No change history.</div>
                            @else
                                <div class="table-responsive">
                                    <table class="table table-bordered mb-0">
                                        <thead>
                                            <tr>
                                                <th>Action</th>
                                                <th>By</th>
                                                <th>Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($shipment->activities as $activity)
                                                <tr>
                                                    <td>{{ $activity->description }}</td>
                                                    <td>{{ $activity->causer->username ?? $activity->causer->name ?? 'System' }}</td>
                                                    <td>{{ $activity->created_at ? $activity->created_at->format('d-M-Y H:i') : '-' }}</td>
                                                </tr>
                                                @php
                                                    $changes = collect(data_get($activity->properties, 'changes', []));
                                                @endphp
                                                @if($changes->isNotEmpty())
                                                    <tr>
                                                        <td colspan="3">
                                                            <div class="small text-muted">
                                                                @foreach($changes as $field => $change)
                                                                    <div>
                                                                        <strong>{{ ucwords(str_replace('_', ' ', $field)) }}:</strong>
                                                                        {{ $change['old'] ?? '-' }} to {{ $change['new'] ?? '-' }}
                                                                    </div>
                                                                @endforeach
                                                            </div>
                                                        </td>
                                                    </tr>
                                                @endif
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

@endsection
